version: '3.9'

services:

  api-gateway:
    build: ../services/api-gateway
    ports:
      - "3000:3000"

  user-service:
    build: ../services/user-service
    ports:
      - "3001:3001"

  product-service:
    build: ../services/product-service
    ports:
      - "3002:3002"